# CI de disparo após o push

# Nome da Pipeline
name: 'CI - Disparo após o push'

# Gatilhos/Triggers - Regras de Disparo
# Gatilho Manual
on: 
  push:
    branches:
      - main
      

#Tarefas dentro da Pipeline
jobs:
    #Nome do Job
    unit-tests:
        # Máquina onde os testes irão rodar
        runs-on: ubuntu-latest

        # Passos do job
        steps:
          # Clone do Projeto
          - uses: actions/checkout@v4

          # Instalação do Node
          - uses: actions/setup-node@v4
            with:
              node-version: 24.x

          # Instalação do Mocha
          - name: Instalando o Mocha
            run: npm i mocha

          # Executar os testes unitários
          - name: Executando os testes unitátios
            run: npx mocha
          
          # Executar os testes unitários
          - name: Salvando relatório de testes
            uses: actions/upload-artifact@v4
            if: ${{ always() }}
            with:
              path: ./mochawesome-report




